"""
Django settings for altsalt_backend project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import dj_database_url
from os.path import join, dirname
from dotenv import load_dotenv
from datetime import timedelta, datetime
from corsheaders.defaults import default_headers

import logging

dotenv_path = join(dirname(__file__), '.env')
load_dotenv(dotenv_path)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.environ.get('DEBUG') == 'True' else False

ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS')
ALLOWED_HOSTS = ALLOWED_HOSTS_STR.split(',')[:-1] if\
    ALLOWED_HOSTS_STR is not None else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # AltSalt

    'django_extensions',
    'graphene_django',
    'graphql_jwt.refresh_token.apps.RefreshTokenConfig',
    'catalog.apps.CatalogConfig',
    'corsheaders',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'catalog.middleware.CacheMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]

ROOT_URLCONF = 'altsalt_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'altsalt_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('DATABASE_NAME'),
        'USER': os.environ.get('DATABASE_USER'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD'),
        'HOST': '',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = "/static/"


# --- AltSalt --- #

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False if\
    os.environ.get('SECURE_SSL_REDIRECT') == 'False' else True

AUTH_USER_MODEL = 'catalog.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'catalog.authentication.EmailBackend',
    'catalog.backends.GraphQLAuthBackend',
    # 'graphql_jwt.backends.JSONWebTokenBackend'
]

STORAGE_LOCATION = os.environ.get('DATABASE_NAME')

PROJECT_NAME = os.environ.get('PROJECT_NAME')
PROJECT_PREFIX = PROJECT_NAME + '_'

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')

MEDIA_URL = '//%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME
MEDIA_ROOT = MEDIA_URL

# For admin files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CORS
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST_STR = os.environ.get('CORS_ORIGIN_WHITELIST')
CORS_ORIGIN_WHITELIST = CORS_ORIGIN_WHITELIST_STR.split(',')[:-1] if\
    CORS_ORIGIN_WHITELIST_STR is not None else []
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control'
]

# CSRF
CSRF_TRUSTED_ORIGINS_STR = os.environ.get('CSRF_TRUSTED_ORIGINS')
CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS_STR.split(',')[:-1] if\
    CSRF_TRUSTED_ORIGINS_STR is not None else []
CSRF_COOKIE_SAMESITE = None
CSRF_COOKIE_SECURE = False if\
    os.environ.get('CSRF_COOKIE_SECURE') == 'False' else True

# SESSION
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = False if\
    os.environ.get('SESSION_COOKIE_SECURE') == 'False' else True

# COOKIE DOMAIN
DOMAIN = os.environ.get('DOMAIN')
CSRF_COOKIE_DOMAIN = DOMAIN if DOMAIN is not None else None
SESSION_COOKIE_DOMAIN = DOMAIN if DOMAIN is not None else None


# AWS S3
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = 'public-read'
AWS_S3_SIGNATURE_VERSION = 's3v4'

# Graphene

GRAPHENE = {
    'SCHEMA': 'altsalt_backend.schema.schema',
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
        'catalog.middleware.DisableIntrospectionMiddleware'
    ],
}

GRAPHQL_JWT = {
    'JWT_HIDE_TOKEN_FIELDS': False,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LONG_RUNNING_REFRESH_TOKEN': True,
    'JWT_EXPIRATION_DELTA': timedelta(minutes=50),
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=30),
    'JWT_COOKIE_SECURE': False if os.environ.get('JWT_COOKIE_SECURE') == 'False' else True
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
    },
}

GRAPHENE_PROTECTOR_DEPTH_LIMIT = 15

# Configure the database from DATABASE_URL (Render / Neon).
# Replaces the Heroku-specific django_heroku helper, which pulled in an
# unpinned psycopg2 (2.9) alongside our psycopg2-binary==2.8.6 pin; 2.9
# is incompatible with Django 3.0's timezone handling ("database
# connection isn't set to UTC"). dj_database_url has no psycopg2 dep.
_db_from_env = dj_database_url.config(conn_max_age=600, ssl_require=True)
if _db_from_env:
    DATABASES['default'].update(_db_from_env)

# Neon routes by SNI, but psycopg2 2.8's bundled libpq predates SNI, so the
# endpoint ID must be passed explicitly via libpq's `options`. Derive it from
# the host (works for both direct and -pooler hosts).
_db_host = DATABASES['default'].get('HOST') or ''
if _db_host.endswith('.neon.tech'):
    _endpoint_id = _db_host.split('.')[0].replace('-pooler', '')
    _db_options = DATABASES['default'].setdefault('OPTIONS', {})
    _db_options['options'] = 'endpoint=%s' % _endpoint_id

DATA_UPLOAD_MAX_MEMORY_SIZE = 17500000
FILE_UPLOAD_MAX_MEMORY_SIZE = 17500000