# Generated by Django 3.0.7 on 2020-07-09 14:25

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=50)),
                ('image_src', models.FileField(upload_to=catalog.models.user.media_upload_path)),
                ('image_caption', models.CharField(max_length=300)),
                ('image_alttext', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'catalog_image',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField()),
                ('listing_description', models.TextField()),
                ('listing_publication_date', models.DateField()),
                ('listing_slug', models.SlugField()),
                ('is_approved', models.BooleanField()),
                ('listing_cover_image_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Image')),
            ],
            options={
                'db_table': 'catalog_listing',
            },
        ),
    ]
