# Generated by Django 3.0.7 on 2020-07-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200709_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_cover_image_id',
            new_name='listing_cover_image',
        ),
    ]
