# Generated by Django 3.0.7 on 2020-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200709_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_title',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
