# Generated by Django 3.0.7 on 2020-07-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_listing_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
