# Generated by Django 3.0.7 on 2020-07-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_listing_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_alttext',
            new_name='alttext',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_src',
            new_name='src',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_cover_image',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_publication_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_location',
            new_name='location',
        ),
    ]
