# Generated by Django 3.0.7 on 2020-07-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200710_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingImage',
            new_name='ListingPreviewImage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listings',
        ),
        migrations.AddField(
            model_name='listing',
            name='preview_images',
            field=models.ManyToManyField(through='catalog.ListingPreviewImage', to='catalog.Listing'),
        ),
    ]
