# Generated by Django 3.0.7 on 2020-07-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200710_1421'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listingpreviewimage',
            constraint=models.UniqueConstraint(fields=('listing', 'image'), name='listing_preview_image_link'),
        ),
        migrations.AlterModelTable(
            name='listingpreviewimage',
            table='catalog_listing_preview_image',
        ),
    ]
