# Generated by Django 3.0.7 on 2020-07-11 10:19

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200710_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(upload_to=catalog.models.user.listing_directory_path),
        ),
        migrations.AlterField(
            model_name='listing',
            name='preview_images',
            field=models.ManyToManyField(through='catalog.ListingPreviewImage', to='catalog.Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to=catalog.models.user.profile_directory_path),
        ),
    ]
