# Generated by Django 3.0.7 on 2020-07-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200711_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cover_image',
        ),
        migrations.CreateModel(
            name='ListingCoverImage',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.Listing')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Image')),
            ],
            options={
                'db_table': 'catalog_listing_cover_image',
            },
        ),
    ]
