# Generated by Django 3.0.7 on 2020-07-16 15:40

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200716_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=catalog.models.models.profile_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='UserListingCreationByline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_user_listing_creation_byline',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_listing_creation_bylines',
            field=models.ManyToManyField(through='catalog.UserListingCreationByline', to='catalog.Listing'),
        ),
        migrations.AddConstraint(
            model_name='userlistingcreationbyline',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='user_listing_creation_link'),
        ),
    ]
