# Generated by Django 3.0.7 on 2020-07-16 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200716_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.Listing'),
        ),
        migrations.CreateModel(
            name='ListingCreationByline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_listing_creation_byline',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_creation_bylines',
            field=models.ManyToManyField(through='catalog.ListingCreationByline', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='listingcreationbyline',
            constraint=models.UniqueConstraint(fields=('listing', 'user'), name='listing_user_creation_link'),
        ),
    ]
