# Generated by Django 3.0.7 on 2020-07-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200716_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlistingcreationbyline',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='userlistingcreationbyline',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='listingcreationbyline',
            name='listing_user_creation_link',
        ),
        migrations.RenameField(
            model_name='listingcreationbyline',
            old_name='priority',
            new_name='listing_priority',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_creation_bylines',
        ),
        migrations.AddField(
            model_name='listingcreationbyline',
            name='user_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_listing_creation_bylines',
            field=models.ManyToManyField(through='catalog.ListingCreationByline', to='catalog.Listing'),
        ),
        migrations.AddConstraint(
            model_name='listingcreationbyline',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='user_listing_creation_link'),
        ),
        migrations.DeleteModel(
            name='UserListingCreationByline',
        ),
    ]
