# Generated by Django 3.0.7 on 2020-07-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200716_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_listing_creation_bylines',
            new_name='listing_creation_bylines',
        ),
    ]
