# Generated by Django 3.0.7 on 2020-07-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200716_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='listing_creation_bylines',
            field=models.ManyToManyField(related_name='ListingCreationByline', through='catalog.ListingCreationByline', to='catalog.Listing'),
        ),
    ]
