# Generated by Django 3.0.7 on 2020-07-17 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20200716_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='listing_creation_bylines',
            field=models.ManyToManyField(related_name='creationBylines', through='catalog.ListingCreationByline', to='catalog.Listing'),
        ),
        migrations.CreateModel(
            name='ListingCollaboratorByline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_priority', models.IntegerField(default=0)),
                ('listing_priority', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_listing_collaborator_byline',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='listing_collaborator_bylines',
            field=models.ManyToManyField(related_name='collaboratorBylines', through='catalog.ListingCollaboratorByline', to='catalog.Listing'),
        ),
        migrations.AddConstraint(
            model_name='listingcollaboratorbyline',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='user_listing_collaborator_link'),
        ),
    ]
