# Generated by Django 3.0.7 on 2020-07-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200717_1315'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='distributiontype',
            table='catalog_distribution_type',
        ),
        migrations.AlterModelTable(
            name='format',
            table='catalog_format',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='catalog_genre',
        ),
        migrations.AlterModelTable(
            name='language',
            table='catalog_language',
        ),
        migrations.AlterModelTable(
            name='length',
            table='catalog_length',
        ),
    ]
