# Generated by Django 3.0.7 on 2020-07-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200717_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='length',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.Length'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ListingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Language')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
            ],
            options={
                'db_table': 'catalog_listing_language',
            },
        ),
        migrations.CreateModel(
            name='ListingGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Genre')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
            ],
            options={
                'db_table': 'catalog_listing_genre',
            },
        ),
        migrations.CreateModel(
            name='ListingFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Format')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
            ],
            options={
                'db_table': 'catalog_listing_format',
            },
        ),
        migrations.CreateModel(
            name='ListingDistributionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.DistributionType')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
            ],
            options={
                'db_table': 'catalog_listing_distribution_type',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='distribution_type',
            field=models.ManyToManyField(through='catalog.ListingDistributionType', to='catalog.DistributionType'),
        ),
        migrations.AddField(
            model_name='listing',
            name='format',
            field=models.ManyToManyField(through='catalog.ListingFormat', to='catalog.Format'),
        ),
        migrations.AddField(
            model_name='listing',
            name='genre',
            field=models.ManyToManyField(through='catalog.ListingGenre', to='catalog.Genre'),
        ),
        migrations.AddField(
            model_name='listing',
            name='language',
            field=models.ManyToManyField(through='catalog.ListingLanguage', to='catalog.Language'),
        ),
        migrations.AddConstraint(
            model_name='listinglanguage',
            constraint=models.UniqueConstraint(fields=('listing', 'language'), name='listing_language_link'),
        ),
        migrations.AddConstraint(
            model_name='listinggenre',
            constraint=models.UniqueConstraint(fields=('listing', 'genre'), name='listing_genre_link'),
        ),
        migrations.AddConstraint(
            model_name='listingformat',
            constraint=models.UniqueConstraint(fields=('listing', 'format'), name='listing_format_link'),
        ),
        migrations.AddConstraint(
            model_name='listingdistributiontype',
            constraint=models.UniqueConstraint(fields=('listing', 'distribution_type'), name='listing_distribution_type_link'),
        ),
    ]
