# Generated by Django 3.0.7 on 2020-07-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20200717_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingformat',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterModelOptions(
            name='listinggenre',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterModelOptions(
            name='listinglanguage',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterField(
            model_name='listingformat',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='catalog.Listing'),
        ),
        migrations.CreateModel(
            name='ListingAvailabilityLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('url', models.CharField(max_length=155)),
                ('priority', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
            ],
            options={
                'db_table': 'catalog_listing_availability_link',
            },
        ),
        migrations.CreateModel(
            name='ListingAdditionalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('url', models.CharField(max_length=155)),
                ('priority', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
            ],
            options={
                'db_table': 'catalog_listing_additional_link',
            },
        ),
    ]
