# Generated by Django 3.0.7 on 2020-07-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200720_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingadditionallink',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='listingavailabilitylink',
            name='url',
            field=models.URLField(),
        ),
    ]
