# Generated by Django 3.0.7 on 2020-07-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20200720_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingadditionallink',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterModelOptions(
            name='listingavailabilitylink',
            options={'ordering': ['-priority']},
        ),
    ]
