# Generated by Django 3.0.7 on 2020-07-20 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200720_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'db_table': 'catalog_continent',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Continent')),
            ],
            options={
                'db_table': 'catalog_culture',
            },
        ),
        migrations.CreateModel(
            name='UserCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Culture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_user_culture',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ListingCultureRepresented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Culture')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
            ],
            options={
                'db_table': 'catalog_listing_culture_represented',
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='culture_represented',
            field=models.ManyToManyField(through='catalog.ListingCultureRepresented', to='catalog.Culture'),
        ),
        migrations.AddField(
            model_name='user',
            name='culture',
            field=models.ManyToManyField(through='catalog.UserCulture', to='catalog.Culture'),
        ),
        migrations.AddConstraint(
            model_name='userculture',
            constraint=models.UniqueConstraint(fields=('user', 'culture'), name='user_culture_link'),
        ),
        migrations.AddConstraint(
            model_name='listingculturerepresented',
            constraint=models.UniqueConstraint(fields=('listing', 'culture'), name='listing_culture_link'),
        ),
    ]
