# Generated by Django 3.0.7 on 2020-07-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20200720_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingCreationByline',
            new_name='ListingCreatorByline',
        ),
        migrations.RemoveConstraint(
            model_name='listingcreatorbyline',
            name='user_listing_creation_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='listing_creation_bylines',
        ),
        migrations.AddField(
            model_name='user',
            name='listing_creator_bylines',
            field=models.ManyToManyField(related_name='creatorBylines', through='catalog.ListingCreatorByline', to='catalog.Listing'),
        ),
        migrations.AddConstraint(
            model_name='listingcreatorbyline',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='user_listing_creator_link'),
        ),
        migrations.AlterModelTable(
            name='listingcreatorbyline',
            table='catalog_listing_creator_byline',
        ),
    ]
