# Generated by Django 3.0.7 on 2020-07-22 21:10

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20200722_2109'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, organization_id=django.db.models.expressions.F('member_id')), name='prevent_self_reference'),
        ),
    ]
