# Generated by Django 3.0.7 on 2020-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20200723_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationmember',
            options={},
        ),
        migrations.RenameField(
            model_name='organizationmember',
            old_name='priority',
            new_name='member_priority',
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='organization_priority',
            field=models.IntegerField(default=0),
        ),
    ]
