# Generated by Django 3.0.7 on 2020-07-29 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20200723_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('preview_text', models.TextField(max_length=200)),
                ('body', models.TextField()),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Image')),
            ],
            options={
                'db_table': 'catalog_article',
            },
        ),
        migrations.CreateModel(
            name='ArticleByline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_priority', models.IntegerField(default=0)),
                ('article_priority', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_article_byline',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='article_bylines',
            field=models.ManyToManyField(related_name='articleBylines', through='catalog.ArticleByline', to='catalog.Article'),
        ),
        migrations.AddConstraint(
            model_name='articlebyline',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='user_article_link'),
        ),
    ]
