# Generated by Django 3.0.7 on 2020-07-29 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20200729_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_approved',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
