# Generated by Django 3.0.7 on 2020-07-31 18:53

import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20200731_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.base.profile_image_path),
        ),
    ]
