# Generated by Django 3.0.7 on 2020-08-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20200731_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_age',
            field=models.BooleanField(default=False),
        ),
    ]
