# Generated by Django 3.0.7 on 2020-08-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_user_show_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'db_table': 'catalog_price_type',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hide_amount', models.BooleanField(default=False)),
                ('details', models.CharField(max_length=100)),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.PriceType')),
            ],
            options={
                'db_table': 'catalog_price',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Price'),
        ),
    ]
