# Generated by Django 3.0.7 on 2020-08-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_auto_20200814_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='hide_amount',
        ),
        migrations.AlterField(
            model_name='price',
            name='details',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
