# Generated by Django 3.0.7 on 2020-08-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20200817_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
            ],
            options={
                'db_table': 'catalog_seo_category',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='seo_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.SeoCategory'),
        ),
    ]
