# Generated by Django 3.0.7 on 2020-09-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_auto_20200903_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default="Hi! I'm a new member of AltSalt."),
        ),
    ]
