# Generated by Django 3.0.7 on 2020-09-19 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_auto_20200917_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_reset_password_request',
            },
        ),
        migrations.AddConstraint(
            model_name='resetpasswordrequest',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='user_token_pair'),
        ),
    ]
