# Generated by Django 3.0.7 on 2020-09-25 17:32

import catalog.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_user_is_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(blank=True, null=True, upload_to=catalog.models.base.profile_image_path)),
                ('large', models.ImageField(blank=True, null=True, upload_to=catalog.models.base.profile_image_path)),
                ('medium', models.ImageField(blank=True, null=True, upload_to=catalog.models.base.profile_image_path)),
                ('small', models.ImageField(blank=True, null=True, upload_to=catalog.models.base.profile_image_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'altsalt_user_profile_image',
            },
        ),
    ]
