# Generated by Django 3.0.7 on 2020-10-06 19:03

import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_userprofileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='image',
            name='large',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AddField(
            model_name='image',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AddField(
            model_name='image',
            name='original',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AddField(
            model_name='image',
            name='small',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default="Hi! I'm a new member."),
        ),
    ]
