# Generated by Django 3.0.7 on 2020-10-07 18:01

import catalog.backends
import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_auto_20201006_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.base.media_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.base.media_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.base.media_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='small',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.base.media_upload_path),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage, upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage, upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage, upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage, upload_to=catalog.models.base.profile_image_path),
        ),
    ]
