# Generated by Django 3.0.7 on 2020-10-09 00:27

import catalog.backends
import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_auto_20201007_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=137, target_width=137), upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=112, target_width=112), upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=600, target_width=600), upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=40, target_width=40), upload_to=catalog.models.base.profile_image_path),
        ),
    ]
