# Generated by Django 3.0.7 on 2020-10-20 21:46

import catalog.backends
import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_auto_20201009_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcoverimage',
            name='alttext',
            field=models.CharField(default='Image alttext', max_length=300),
        ),
        migrations.AddField(
            model_name='listingcoverimage',
            name='caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='listingcoverimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=137, target_width=137), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AddField(
            model_name='listingcoverimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=112, target_width=112), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AddField(
            model_name='listingcoverimage',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=600, target_width=600), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AddField(
            model_name='listingcoverimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=40, target_width=40), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AddField(
            model_name='listingpreviewimage',
            name='alttext',
            field=models.CharField(default='Image alttext', max_length=300),
        ),
        migrations.AddField(
            model_name='listingpreviewimage',
            name='caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='listingpreviewimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=137, target_width=137), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AddField(
            model_name='listingpreviewimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=112, target_width=112), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AddField(
            model_name='listingpreviewimage',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=600, target_width=600), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AddField(
            model_name='listingpreviewimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=40, target_width=40), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AddConstraint(
            model_name='listingcoverimage',
            constraint=models.UniqueConstraint(fields=('listing', 'image'), name='listing_cover_image_link'),
        ),
    ]
