# Generated by Django 3.0.7 on 2020-10-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20201020_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_approved',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default="The author(s) haven't provided a description yet.", null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
