# Generated by Django 3.0.7 on 2020-10-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_auto_20201021_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='length',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Length'),
        ),
    ]
