# Generated by Django 3.0.7 on 2020-10-21 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_auto_20201021_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcoverimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Image'),
        ),
    ]
