# Generated by Django 3.0.7 on 2020-10-28 00:05

import catalog.backends
import catalog.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_auto_20201021_1911'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listingcoverimage',
            name='listing_cover_image_link',
        ),
        migrations.RemoveConstraint(
            model_name='listingpreviewimage',
            name='listing_preview_image_link',
        ),
        migrations.RenameField(
            model_name='listingpreviewimage',
            old_name='priority',
            new_name='index',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='preview_images',
        ),
        migrations.RemoveField(
            model_name='listingcoverimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=555, target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=275, target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=180, target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Image'),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=555, target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing'),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=275, target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=180, target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
    ]
