# Generated by Django 3.0.10 on 2020-10-31 16:39

import catalog.backends
import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0056_auto_20201028_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingpreviewimage',
            options={'ordering': ['index']},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='slug',
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=555, target_width=767), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=275, target_width=767), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=180, target_width=767), upload_to=catalog.models.base.listing_preview_image_path),
        ),
    ]
