# Generated by Django 3.0.10 on 2020-10-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_auto_20201031_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='length',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='length',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
