# Generated by Django 3.0.10 on 2020-11-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_auto_20201031_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
