# Generated by Django 3.0.10 on 2020-11-03 14:49

import builtins
import catalog.backends
import catalog.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_auto_20201102_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcoverimage',
            name='listing_new',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing'),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=555, target_image_id=builtins.id, target_image_model='ListingCoverImage', target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='listing',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=275, target_image_id=builtins.id, target_image_model='ListingCoverImage', target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=180, target_image_id=builtins.id, target_image_model='ListingCoverImage', target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=555, target_image_id=builtins.id, target_image_model='ListingPreviewImage', target_width=767), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=275, target_image_id=builtins.id, target_image_model='ListingPreviewImage', target_width=767), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=180, target_image_id=builtins.id, target_image_model='ListingPreviewImage', target_width=767), upload_to=catalog.models.base.listing_preview_image_path),
        ),
    ]
