# Generated by Django 3.0.10 on 2020-11-03 14:50

from django.db import migrations


def migrate_cover_image(apps, schema_editor):
    cover_image_model = apps.get_model('catalog', 'ListingCoverImage')

    for cover_image in cover_image_model.objects.all():

        cover_image.listing_new_id = cover_image.listing
        cover_image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_auto_20201103_1449'),
    ]

    operations = [
        migrations.RunPython(migrate_cover_image)
    ]
