# Generated by Django 3.0.10 on 2020-11-03 14:57

import catalog.backends
import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_auto_20201103_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingcoverimage',
            old_name='listing',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=555, target_image_id=models.AutoField(primary_key=True, serialize=False), target_image_model='ListingCoverImage', target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=275, target_image_id=models.AutoField(primary_key=True, serialize=False), target_image_model='ListingCoverImage', target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(save_thumbnails=True, target_height=180, target_image_id=models.AutoField(primary_key=True, serialize=False), target_image_model='ListingCoverImage', target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
    ]
