# Generated by Django 3.0.10 on 2020-11-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_auto_20201103_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingcoverimage',
            old_name='listing_new',
            new_name='listing',
        ),
    ]
