# Generated by Django 3.0.10 on 2020-11-03 21:00

import catalog.backends
import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_auto_20201103_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcoverimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=555, target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=275, target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=180, target_width=767), upload_to=catalog.models.base.listing_cover_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=555, target_width=767), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=275, target_width=767), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=180, target_width=767), upload_to=catalog.models.base.listing_preview_image_path),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='large',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=137, target_width=137), upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=112, target_width=112), upload_to=catalog.models.base.profile_image_path),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='small',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=40, target_width=40), upload_to=catalog.models.base.profile_image_path),
        ),
    ]
