# Generated by Django 3.0.10 on 2020-11-06 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0064_auto_20201103_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcollaboratorbyline',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingcollaboratorbyline',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingcreatorbyline',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingcreatorbyline',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='members',
            field=models.ManyToManyField(through='catalog.OrganizationMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
