# Generated by Django 3.0.10 on 2020-11-09 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0065_auto_20201106_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcollaboratorbyline',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listingcreatorbyline',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creation_requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
