# Generated by Django 3.0.10 on 2020-11-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_auto_20201109_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingcoverimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listingpreviewimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='alttext',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='listingcoverimage',
            name='alttext',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='listingpreviewimage',
            name='alttext',
            field=models.CharField(default='', max_length=300),
        ),
    ]
