# Generated by Django 3.0.10 on 2020-11-12 16:14

import catalog.backends
import catalog.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0067_auto_20201112_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='featured_image',
        ),
        migrations.CreateModel(
            name='ArticleFeaturedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alttext', models.CharField(default='', max_length=300)),
                ('original', models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.article_cover_image_path)),
                ('large', models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=555, target_width=767), upload_to=catalog.models.base.article_cover_image_path)),
                ('medium', models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=275, target_width=767), upload_to=catalog.models.base.article_cover_image_path)),
                ('small', models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=180, target_width=767), upload_to=catalog.models.base.article_cover_image_path)),
                ('article', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
