# Generated by Django 3.0.10 on 2020-11-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0068_auto_20201112_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefeaturedimage',
            name='caption',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
