# Generated by Django 3.0.10 on 2020-11-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0069_articlefeaturedimage_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
