# Generated by Django 3.0.10 on 2020-11-14 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0070_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'db_table': 'catalog_tag',
            },
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ListingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tag')),
            ],
            options={
                'db_table': 'catalog_listing_tag',
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='tag',
            field=models.ManyToManyField(through='catalog.ListingTag', to='catalog.Tag'),
        ),
        migrations.AddConstraint(
            model_name='listingtag',
            constraint=models.UniqueConstraint(fields=('listing', 'tag'), name='listing_tag_link'),
        ),
    ]
