# Generated by Django 3.0.10 on 2020-11-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0071_auto_20201114_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
