# Generated by Django 3.0.10 on 2020-11-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_auto_20201115_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributiontype',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='distributiontype',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Price'),
        ),
    ]
