# Generated by Django 3.0.10 on 2020-11-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_auto_20201115_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
    ]
