# Generated by Django 3.0.10 on 2020-11-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0076_listing_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_newsletter_popup', models.BooleanField(default=True)),
                ('show_featured', models.BooleanField(default=True)),
                ('featured_heading', models.CharField(default='Featured', max_length=180)),
            ],
        ),
    ]
