# Generated by Django 3.0.10 on 2020-11-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0077_editorialsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorialsettings',
            options={'verbose_name': 'Editorial Settings', 'verbose_name_plural': 'Editorial Settings'},
        ),
    ]
