# Generated by Django 3.0.10 on 2020-11-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0078_auto_20201120_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Culture',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='ListingCultureRepresented',
            new_name='ListingCountryRepresented',
        ),
        migrations.RenameModel(
            old_name='UserCulture',
            new_name='UserCountry',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='listingcountryrepresented',
            name='listing_culture_link',
        ),
        migrations.RemoveConstraint(
            model_name='usercountry',
            name='user_culture_link',
        ),
        migrations.RenameField(
            model_name='listingcountryrepresented',
            old_name='culture',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='usercountry',
            old_name='culture',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='culture_represented',
        ),
        migrations.RemoveField(
            model_name='user',
            name='culture',
        ),
        migrations.AddField(
            model_name='listing',
            name='country_represented',
            field=models.ManyToManyField(through='catalog.ListingCountryRepresented', to='catalog.Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ManyToManyField(through='catalog.UserCountry', to='catalog.Country'),
        ),
        migrations.AddConstraint(
            model_name='listingcountryrepresented',
            constraint=models.UniqueConstraint(fields=('listing', 'country'), name='listing_country_link'),
        ),
        migrations.AddConstraint(
            model_name='usercountry',
            constraint=models.UniqueConstraint(fields=('user', 'country'), name='user_country_link'),
        ),
        migrations.AlterModelTable(
            name='country',
            table='catalog_country',
        ),
        migrations.AlterModelTable(
            name='listingcountryrepresented',
            table='catalog_listing_country_represented',
        ),
        migrations.AlterModelTable(
            name='usercountry',
            table='catalog_user_country',
        ),
    ]
