# Generated by Django 3.0.10 on 2020-11-23 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0079_auto_20201123_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'db_table': 'catalog_identity',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Identity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_user_identity',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ListingIdentityRepresented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Identity')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
            ],
            options={
                'db_table': 'catalog_listing_identity_represented',
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='identity_represented',
            field=models.ManyToManyField(through='catalog.ListingIdentityRepresented', to='catalog.Identity'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.ManyToManyField(through='catalog.UserIdentity', to='catalog.Identity'),
        ),
        migrations.AddConstraint(
            model_name='useridentity',
            constraint=models.UniqueConstraint(fields=('user', 'identity'), name='user_identity_link'),
        ),
        migrations.AddConstraint(
            model_name='listingidentityrepresented',
            constraint=models.UniqueConstraint(fields=('listing', 'identity'), name='listing_identity_link'),
        ),
    ]
