# Generated by Django 3.0.10 on 2020-11-24 02:01

from django.db import migrations
from django.conf import settings
from django.template.defaultfilters import slugify


def import_countries_by_continent(apps, file_path, continent_name):

    Continent = apps.get_model('catalog', 'Continent')
    Country = apps.get_model('catalog', 'Country')

    continent_slug = slugify(continent_name)

    if not Continent.objects.filter(slug=continent_slug).exists():
        new_continent = Continent(name=continent_name.strip(), slug=continent_slug)
        new_continent.save()

    continent_object = Continent.objects.get(slug=continent_slug)
    continent_object.name = continent_object.name.strip()
    continent_object.save()

    with open(file_path) as fp:
        lines = fp.readlines()
        for line in lines:
            country_slug = slugify(line)
            if not Country.objects.filter(slug=country_slug).exists():
                new_country = Country(name=line.strip(), slug=country_slug)
                new_country.save()

            country_object = Country.objects.get(slug=country_slug)
            country_object.name = country_object.name.strip()
            country_object.continent = continent_object
            country_object.save()


def import_all_countries(apps, schema_editor):

    countries_path = '{0}/catalog/data/countries/'.format(settings.BASE_DIR)
    africa_countries = '{0}/africa.txt'.format(countries_path)
    asia_countries = '{0}/asia.txt'.format(countries_path)
    europe_countries = '{0}/europe.txt'.format(countries_path)
    north_america_countries = '{0}/north_america.txt'.format(countries_path)
    oceania_countries = '{0}/oceania.txt'.format(countries_path)
    south_america_countries = '{0}/south_america.txt'.format(countries_path)

    import_countries_by_continent(apps, africa_countries, 'Africa')
    import_countries_by_continent(apps, asia_countries, 'Asia')
    import_countries_by_continent(apps, europe_countries, 'Europe')
    import_countries_by_continent(apps, north_america_countries, 'North America')
    import_countries_by_continent(apps, oceania_countries, 'Oceania')
    import_countries_by_continent(apps, south_america_countries, 'South America')


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0080_auto_20201123_2128'),
    ]

    operations = [
        migrations.RunPython(import_all_countries, reverse),
    ]
