# Generated by Django 3.0.10 on 2020-12-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0081_auto_20201124_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='identity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Identities'},
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
