# Generated by Django 3.0.10 on 2020-12-12 04:09

import catalog.backends
import catalog.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0082_auto_20201209_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=catalog.backends.CatalogImageStorage, upload_to=catalog.models.base.listing_upload_path)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
            ],
        ),
    ]
