# Generated by Django 3.0.10 on 2020-12-14 19:33

import catalog.backends
import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0083_listingupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingupload',
            name='allow_downloads',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listingupload',
            name='file',
            field=models.FileField(blank=True, null=True, storage=catalog.backends.CatalogImageStorage(), upload_to=catalog.models.base.listing_upload_path),
        ),
    ]
