# Generated by Django 3.0.10 on 2021-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0084_auto_20201214_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=125),
        ),
    ]
