# Generated by Django 3.0.10 on 2021-01-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0085_auto_20210108_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, max_length=125),
        ),
    ]
