# Generated by Django 3.0.10 on 2021-01-24 23:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0086_auto_20210108_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('info', models.TextField(blank=True, default='')),
                ('is_approved', models.BooleanField(default=False)),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Price')),
            ],
            options={
                'db_table': 'catalog_submission',
            },
        ),
    ]
