# Generated by Django 3.0.10 on 2021-01-24 23:37

import catalog.backends
import catalog.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0087_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, storage=catalog.backends.CatalogImageStorage(), upload_to=catalog.models.base.submission_upload_path),
        ),
        migrations.AddField(
            model_name='submission',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing'),
        ),
        migrations.CreateModel(
            name='SubmissionAvailabilityLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('url', models.URLField()),
                ('priority', models.IntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Submission')),
            ],
            options={
                'db_table': 'catalog_submission_availability_link',
                'ordering': ['-priority'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubmissionAdditionalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('url', models.URLField()),
                ('priority', models.IntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Submission')),
            ],
            options={
                'db_table': 'catalog_submission_additional_link',
                'ordering': ['-priority'],
                'abstract': False,
            },
        ),
    ]
