# Generated by Django 3.0.10 on 2021-01-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0088_auto_20210124_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='info',
            new_name='additional_info',
        ),
    ]
