# Generated by Django 3.0.10 on 2021-01-31 01:41

import catalog.backends
import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0089_auto_20210127_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, storage=catalog.backends.CatalogImageStorage(default_acl='private'), upload_to=catalog.models.base.submission_upload_path),
        ),
    ]
