# Generated by Django 3.0.10 on 2021-02-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0092_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingupload',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
