# Generated by Django 3.0.10 on 2021-02-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0093_listingupload_is_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='custom_author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='listing',
            name='show_custom_author',
            field=models.BooleanField(default=False),
        ),
    ]
