# Generated by Django 3.0.10 on 2021-02-23 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0094_auto_20210222_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'catalog_thread',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ListingThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Thread')),
            ],
            options={
                'db_table': 'catalog_listing_thread',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_root', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Thread')),
            ],
            options={
                'db_table': 'catalog_comment',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='listingthread',
            constraint=models.UniqueConstraint(fields=('listing', 'thread'), name='listing_thread_link'),
        ),
    ]
