# Generated by Django 3.0.10 on 2021-02-24 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0096_auto_20210223_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingthread',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='listingthread',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
