# Generated by Django 3.0.10 on 2021-02-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0100_auto_20210227_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='candidate_token',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
