# Generated by Django 3.0.10 on 2021-03-06 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0101_auto_20210228_0431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('SW', 'Semiweekly'), ('W', 'Weekly'), ('X', 'OFF')], default='SW', max_length=2),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
