# Generated by Django 3.0.10 on 2021-03-06 22:02

from django.db import migrations


def create_default_notification_settings(apps, schema_editor):

    User = apps.get_model('catalog', 'User')
    NotificationSettings = apps.get_model('catalog', 'NotificationSettings')
    for person in User.objects.all():
        notification_settings = NotificationSettings(user=person)
        notification_settings.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0102_auto_20210306_2229'),
    ]

    operations = [
        migrations.RunPython(create_default_notification_settings, backwards),
    ]
