# Generated by Django 3.0.10 on 2021-03-07 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0103_auto_20210306_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettingsAuthorizedUpdate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_notification_settings_authorized_update',
            },
        ),
        migrations.AddConstraint(
            model_name='notificationsettingsauthorizedupdate',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='user_notification_settings_update_pair'),
        ),
    ]
