# Generated by Django 3.0.10 on 2021-03-10 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0104_auto_20210307_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_signup_code',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='signup_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.SignupCode'),
        ),
    ]
