# Generated by Django 3.0.10 on 2021-03-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0105_auto_20210310_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_full_bleed',
            field=models.BooleanField(default=False),
        ),
    ]
