# Generated by Django 3.0.10 on 2021-03-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0106_auto_20210319_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_script',
            field=models.TextField(blank=True, default=''),
        ),
    ]
