# Generated by Django 3.0.10 on 2021-03-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0107_article_post_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingupload',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
