# Generated by Django 3.0.10 on 2021-04-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0108_listingupload_is_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tag')),
            ],
            options={
                'db_table': 'catalog_article_tag',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ArticleLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Article')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Language')),
            ],
            options={
                'db_table': 'catalog_article_language',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ArticleIdentityRepresented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Article')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Identity')),
            ],
            options={
                'db_table': 'catalog_article_identity_represented',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ArticleGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Article')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Genre')),
            ],
            options={
                'db_table': 'catalog_article_genre',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ArticleFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='catalog.Article')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Format')),
            ],
            options={
                'db_table': 'catalog_article_format',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ArticleDistributionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Article')),
                ('distribution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.DistributionType')),
            ],
            options={
                'db_table': 'catalog_article_distribution_type',
            },
        ),
        migrations.CreateModel(
            name='ArticleCountryRepresented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Article')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Country')),
            ],
            options={
                'db_table': 'catalog_article_country_represented',
                'ordering': ['-priority'],
            },
        ),
        migrations.AddConstraint(
            model_name='articletag',
            constraint=models.UniqueConstraint(fields=('article', 'tag'), name='article_tag_link'),
        ),
        migrations.AddConstraint(
            model_name='articlelanguage',
            constraint=models.UniqueConstraint(fields=('article', 'language'), name='article_language_link'),
        ),
        migrations.AddConstraint(
            model_name='articleidentityrepresented',
            constraint=models.UniqueConstraint(fields=('article', 'identity'), name='article_identity_link'),
        ),
        migrations.AddConstraint(
            model_name='articlegenre',
            constraint=models.UniqueConstraint(fields=('article', 'genre'), name='article_genre_link'),
        ),
        migrations.AddConstraint(
            model_name='articleformat',
            constraint=models.UniqueConstraint(fields=('article', 'format'), name='article_format_link'),
        ),
        migrations.AddConstraint(
            model_name='articledistributiontype',
            constraint=models.UniqueConstraint(fields=('article', 'distribution_type'), name='article_distribution_type_link'),
        ),
        migrations.AddConstraint(
            model_name='articlecountryrepresented',
            constraint=models.UniqueConstraint(fields=('article', 'country'), name='article_country_link'),
        ),
    ]
