# Generated by Django 3.0.10 on 2021-04-12 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0109_auto_20210412_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.ContentRating'),
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Price'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlebyline',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
