# Generated by Django 3.0.10 on 2021-04-12 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0110_auto_20210412_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Length'),
        ),
    ]
