# Generated by Django 3.0.10 on 2021-04-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0111_article_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_excerpt',
            field=models.BooleanField(default=False),
        ),
    ]
