# Generated by Django 3.0.10 on 2021-04-16 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0112_article_is_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlebyline',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_byline_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=125),
        ),
    ]
