# Generated by Django 3.0.10 on 2021-04-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0113_auto_20210416_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
