# Generated by Django 3.0.10 on 2021-04-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0114_remove_article_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingThread',
            new_name='ContentThread',
        ),
    ]
