# Generated by Django 3.0.10 on 2021-04-20 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalog', '0115_auto_20210419_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentthread',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='contentthread',
            name='listing',
            field=models.PositiveIntegerField(),
        ),
    ]
