# Generated by Django 3.0.10 on 2021-04-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0116_auto_20210420_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentthread',
            old_name='listing',
            new_name='object_id',
        ),
    ]
