# Generated by Django 3.0.10 on 2021-04-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0117_auto_20210420_0003'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentthread',
            name='listing_thread_link',
        ),
        migrations.AlterModelTable(
            name='contentthread',
            table='catalog_content_thread',
        ),
    ]
