# Generated by Django 3.0.10 on 2021-05-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0118_auto_20210420_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subheading',
            field=models.CharField(blank=True, default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
