# Generated by Django 3.0.10 on 2021-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0119_auto_20210504_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_status',
            field=models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Public')], default='P', max_length=2),
        ),
    ]
