# Generated by Django 3.0.10 on 2021-05-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0120_article_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_status',
            field=models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Public')], default='D', max_length=2),
        ),
    ]
