# Generated by Django 3.0.10 on 2021-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0121_auto_20210513_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_full_bleed_alignment',
            field=models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right')], default='C', max_length=2),
        ),
    ]
