# Generated by Django 3.0.10 on 2021-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0122_article_featured_image_full_bleed_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_full_bleed_fit',
            field=models.CharField(choices=[('Cover', 'Cover'), ('Contain', 'Contain')], default='Cover', max_length=7),
        ),
    ]
