# Generated by Django 3.0.10 on 2021-07-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0124_auto_20210703_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('publish_status', models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Public')], default='D', max_length=2)),
            ],
            options={
                'db_table': 'catalog_collection',
            },
        ),
    ]
