# Generated by Django 3.0.10 on 2021-07-03 15:47

import catalog.backends
import catalog.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0125_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_priority', models.IntegerField(default=0)),
                ('listing_priority', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Collection')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Listing')),
            ],
            options={
                'db_table': 'catalog_collection_listing',
            },
        ),
        migrations.CreateModel(
            name='CollectionCoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alttext', models.CharField(default='', max_length=300)),
                ('original', models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.collection_cover_image_path)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('collection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Collection')),
            ],
            options={
                'db_table': 'catalog_collection_cover_image',
            },
        ),
        migrations.CreateModel(
            name='CollectionByline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_priority', models.IntegerField(default=0)),
                ('collection_priority', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Collection')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_byline_requester', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_collection_byline',
            },
        ),
        migrations.CreateModel(
            name='CollectionArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_priority', models.IntegerField(default=0)),
                ('article_priority', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Article')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Collection')),
            ],
            options={
                'db_table': 'catalog_collection_article',
            },
        ),
        migrations.AddConstraint(
            model_name='collectionlisting',
            constraint=models.UniqueConstraint(fields=('collection', 'listing'), name='collection_listing_link'),
        ),
        migrations.AddConstraint(
            model_name='collectionbyline',
            constraint=models.UniqueConstraint(fields=('user', 'collection'), name='user_collection_link'),
        ),
        migrations.AddConstraint(
            model_name='collectionarticle',
            constraint=models.UniqueConstraint(fields=('collection', 'article'), name='collection_article_link'),
        ),
    ]
