# Generated by Django 3.0.10 on 2021-07-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0126_auto_20210703_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='dedication',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='collection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
