# Generated by Django 3.0.10 on 2021-07-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0127_auto_20210703_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionbyline',
            options={'ordering': ['-collection_priority']},
        ),
        migrations.CreateModel(
            name='CollectionAdditionalResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_priority', models.IntegerField(default=0)),
                ('article_priority', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Article')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Collection')),
            ],
            options={
                'db_table': 'catalog_collection_additional_resources',
            },
        ),
        migrations.AddConstraint(
            model_name='collectionadditionalresources',
            constraint=models.UniqueConstraint(fields=('collection', 'article'), name='collection_additional_resources_link'),
        ),
    ]
