# Generated by Django 3.0.10 on 2021-07-04 15:21

import catalog.backends
import catalog.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0128_auto_20210704_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDedicationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alttext', models.CharField(default='', max_length=300)),
                ('original', models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.collection_cover_image_path)),
                ('collection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Collection')),
            ],
            options={
                'db_table': 'catalog_collection_dedication_image',
            },
        ),
    ]
