# Generated by Django 3.0.10 on 2021-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0129_collectiondedicationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='listingupload',
            name='html_location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
