# Generated by Django 3.0.10 on 2021-08-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0130_auto_20210807_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='publish_status',
            field=models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Public')], default='D', max_length=2),
        ),
    ]
