# Generated by Django 3.0.10 on 2021-08-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0131_listing_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='publish_status',
            field=models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Public')], default='P', max_length=2),
        ),
    ]
