# Generated by Django 3.0.10 on 2021-08-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0132_auto_20210807_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='publish_status',
            field=models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Public')], default='D', max_length=2),
        ),
    ]
