# Generated by Django 3.0.10 on 2021-08-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalog', '0133_auto_20210815_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Collection')),
            ],
            options={
                'db_table': 'catalog_collection_section',
            },
        ),
        migrations.CreateModel(
            name='CollectionSectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('collection_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CollectionSection')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'catalog_collection_section_item',
            },
        ),
    ]
