# Generated by Django 3.0.10 on 2021-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0134_collectionsection_collectionsectionitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='description',
            new_name='introduction',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='title',
        ),
        migrations.AddField(
            model_name='collection',
            name='title1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='title2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='title3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
