# Generated by Django 3.0.10 on 2021-08-30 15:26

import catalog.backends
import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0136_collectionintroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsection',
            name='hide_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collectiondedicationimage',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.collection_dedication_image_path),
        ),
        migrations.AlterField(
            model_name='collectionintroimage',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.collection_intro_image_path),
        ),
    ]
