# Generated by Django 3.0.10 on 2021-08-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0137_auto_20210830_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionsectionitem',
            old_name='title',
            new_name='subtitle',
        ),
        migrations.AlterField(
            model_name='collectionsection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
