# Generated by Django 3.0.10 on 2021-08-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0138_auto_20210830_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='collectionarticle',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionlisting',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionlisting',
            name='listing',
        ),
        migrations.DeleteModel(
            name='CollectionAdditionalResources',
        ),
        migrations.DeleteModel(
            name='CollectionArticle',
        ),
        migrations.DeleteModel(
            name='CollectionListing',
        ),
    ]
