# Generated by Django 3.0.10 on 2021-08-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalog', '0139_auto_20210830_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('hide_header', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='catalog.Collection')),
            ],
            options={
                'db_table': 'catalog_collection_page_section',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'catalog_page_section',
            },
        ),
        migrations.CreateModel(
            name='PageSectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('page_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PageSection')),
            ],
            options={
                'db_table': 'catalog_page_section_item',
            },
        ),
        migrations.RemoveField(
            model_name='collectionsectionitem',
            name='collection_section',
        ),
        migrations.RemoveField(
            model_name='collectionsectionitem',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='CollectionSection',
        ),
        migrations.DeleteModel(
            name='CollectionSectionItem',
        ),
        migrations.AddField(
            model_name='collectionpagesection',
            name='page_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.PageSection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='page_section',
            field=models.ManyToManyField(through='catalog.CollectionPageSection', to='catalog.PageSection'),
        ),
        migrations.AddConstraint(
            model_name='collectionpagesection',
            constraint=models.UniqueConstraint(fields=('collection', 'page_section'), name='collection_page_section_link'),
        ),
    ]
