# Generated by Django 3.0.10 on 2021-08-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0140_auto_20210830_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='intro_background_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='intro_font_color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
