# Generated by Django 3.0.10 on 2021-08-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalog', '0141_auto_20210830_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageSectionItem',
            new_name='PageSectionEntry',
        ),
        migrations.AlterModelTable(
            name='pagesectionentry',
            table='catalog_page_section_entry',
        ),
    ]
