# Generated by Django 3.0.10 on 2021-08-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0142_auto_20210830_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesectionentry',
            name='desktop_layout',
            field=models.CharField(choices=[('one-column', 'One Column'), ('two-column', 'Two Column')], default='one-column', max_length=10),
        ),
    ]
