# Generated by Django 3.0.10 on 2021-08-31 15:02

import catalog.backends
import catalog.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0143_pagesectionentry_desktop_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=False)),
                ('publish_status', models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Public')], default='D', max_length=2)),
                ('content_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.ContentRating')),
            ],
            options={
                'db_table': 'catalog_art',
            },
        ),
        migrations.CreateModel(
            name='ArtUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alttext', models.CharField(default='', max_length=300)),
                ('original', models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.listing_cover_image_path)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Art')),
            ],
            options={
                'db_table': 'catalog_art_upload',
            },
        ),
        migrations.CreateModel(
            name='ArtTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Art')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tag')),
            ],
            options={
                'db_table': 'catalog_art_tag',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ArtIdentityRepresented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Art')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Identity')),
            ],
            options={
                'db_table': 'catalog_art_identity_represented',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ArtGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Art')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Genre')),
            ],
            options={
                'db_table': 'catalog_art_genre',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ArtCountryRepresented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Art')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Country')),
            ],
            options={
                'db_table': 'catalog_art_country_represented',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='ArtByline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_priority', models.IntegerField(default=0)),
                ('art_priority', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Art')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_byline_requester', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_art_byline',
            },
        ),
        migrations.AddConstraint(
            model_name='arttag',
            constraint=models.UniqueConstraint(fields=('art', 'tag'), name='art_tag_link'),
        ),
        migrations.AddConstraint(
            model_name='artidentityrepresented',
            constraint=models.UniqueConstraint(fields=('art', 'identity'), name='art_identity_link'),
        ),
        migrations.AddConstraint(
            model_name='artgenre',
            constraint=models.UniqueConstraint(fields=('art', 'genre'), name='art_genre_link'),
        ),
        migrations.AddConstraint(
            model_name='artcountryrepresented',
            constraint=models.UniqueConstraint(fields=('art', 'country'), name='art_country_link'),
        ),
        migrations.AddConstraint(
            model_name='artbyline',
            constraint=models.UniqueConstraint(fields=('user', 'art'), name='user_art_link'),
        ),
    ]
