# Generated by Django 3.0.10 on 2021-09-02 13:25

import catalog.backends
import catalog.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0144_auto_20210831_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artupload',
            name='original',
            field=models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.art_upload_path),
        ),
    ]
