# Generated by Django 3.0.10 on 2021-09-02 13:27

import catalog.backends
import catalog.models.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0145_auto_20210902_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=False)),
                ('src_1080', models.CharField(max_length=500)),
                ('src_720', models.CharField(max_length=500)),
                ('src_360', models.CharField(max_length=500)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('playtime', models.FloatField(default=0)),
                ('publish_status', models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Public')], default='D', max_length=2)),
                ('content_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.ContentRating')),
            ],
            options={
                'db_table': 'catalog_movie',
            },
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movie')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tag')),
            ],
            options={
                'db_table': 'catalog_movie_tag',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='MovieIdentityRepresented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Identity')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movie')),
            ],
            options={
                'db_table': 'catalog_movie_identity_represented',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movie')),
            ],
            options={
                'db_table': 'catalog_movie_genre',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='MovieCoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alttext', models.CharField(default='', max_length=300)),
                ('original', models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.movie_upload_path)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movie')),
            ],
            options={
                'db_table': 'catalog_movie_upload',
            },
        ),
        migrations.CreateModel(
            name='MovieCountryRepresented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Country')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movie')),
            ],
            options={
                'db_table': 'catalog_movie_country_represented',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='MovieByline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_priority', models.IntegerField(default=0)),
                ('movie_priority', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movie')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_byline_requester', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_movie_byline',
            },
        ),
        migrations.AddConstraint(
            model_name='movietag',
            constraint=models.UniqueConstraint(fields=('movie', 'tag'), name='movie_tag_link'),
        ),
        migrations.AddConstraint(
            model_name='movieidentityrepresented',
            constraint=models.UniqueConstraint(fields=('movie', 'identity'), name='movie_identity_link'),
        ),
        migrations.AddConstraint(
            model_name='moviegenre',
            constraint=models.UniqueConstraint(fields=('movie', 'genre'), name='movie_genre_link'),
        ),
        migrations.AddConstraint(
            model_name='moviecountryrepresented',
            constraint=models.UniqueConstraint(fields=('movie', 'country'), name='movie_country_link'),
        ),
        migrations.AddConstraint(
            model_name='moviebyline',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='user_movie_link'),
        ),
    ]
