# Generated by Django 3.0.10 on 2021-09-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0146_auto_20210902_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecoverimage',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Movie'),
        ),
        migrations.AlterModelTable(
            name='moviecoverimage',
            table='catalog_movie_cover_image',
        ),
    ]
