# Generated by Django 3.0.10 on 2021-09-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0147_auto_20210902_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='intro_background_color',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
