# Generated by Django 3.0.10 on 2021-09-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0148_auto_20210905_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'catalog_pull_quote',
            },
        ),
    ]
