# Generated by Django 3.0.10 on 2021-09-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0149_pullquote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagesectionentry',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='collection',
            name='sibling_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Collection'),
        ),
        migrations.AlterField(
            model_name='collectionpagesection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Collection'),
        ),
    ]
