# Generated by Django 3.0.10 on 2021-09-11 11:58

import catalog.backends
import catalog.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('catalog', '0150_auto_20210907_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('publish_status', models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Public')], default='D', max_length=2)),
            ],
            options={
                'db_table': 'catalog_playlist',
            },
        ),
        migrations.AlterModelOptions(
            name='collectionpagesection',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='pagesectionentry',
            options={'ordering': ['priority']},
        ),
        migrations.CreateModel(
            name='PlaylistEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Playlist')),
            ],
            options={
                'db_table': 'catalog_playlist_entry',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistCoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alttext', models.CharField(default='', max_length=300)),
                ('original', models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.playlist_cover_image_path)),
                ('playlist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Playlist')),
            ],
            options={
                'db_table': 'catalog_playlist_cover_image',
            },
        ),
    ]
