# Generated by Django 3.0.10 on 2021-09-12 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0151_auto_20210911_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, default='', max_length=100)),
                ('title2', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('publish_status', models.CharField(choices=[('D', 'Draft'), ('U', 'Unlisted'), ('P', 'Public')], default='D', max_length=2)),
            ],
            options={
                'db_table': 'catalog_project',
            },
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Collection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Project')),
            ],
            options={
                'db_table': 'catalog_project_collection',
                'ordering': ['priority'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectcollection',
            constraint=models.UniqueConstraint(fields=('project', 'collection'), name='project_collection_link'),
        ),
    ]
