# Generated by Django 3.0.10 on 2021-09-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0152_auto_20210912_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='postscript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='title1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
