# Generated by Django 3.0.10 on 2021-09-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0153_auto_20210916_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='preface_background_color',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
