# Generated by Django 3.0.10 on 2021-09-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0154_collection_preface_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='hide_bylines',
            field=models.BooleanField(default=False),
        ),
    ]
