# Generated by Django 3.0.10 on 2021-09-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0155_listing_hide_bylines'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='custom_author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='show_custom_author',
            field=models.BooleanField(default=False),
        ),
    ]
