# Generated by Django 3.0.10 on 2021-09-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0156_auto_20210924_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hide_bylines',
            field=models.BooleanField(default=False),
        ),
    ]
