# Generated by Django 3.0.10 on 2021-09-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0157_article_hide_bylines'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='custom_author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='art',
            name='hide_bylines',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='art',
            name='show_custom_author',
            field=models.BooleanField(default=False),
        ),
    ]
