# Generated by Django 3.0.10 on 2021-09-26 12:09

import catalog.backends
import catalog.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0158_auto_20210924_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alttext', models.CharField(default='', max_length=300)),
                ('original', models.ImageField(blank=True, null=True, storage=catalog.backends.ThumbnailImageStorage(target_height=2382, target_width=1588), upload_to=catalog.models.base.project_cover_image_path)),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Project')),
            ],
            options={
                'db_table': 'catalog_project_cover_image',
            },
        ),
    ]
